services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - minha_rede

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "${KEYCLOAK_ADMIN_USERNAME}"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"

      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres/${POSTGRES_DB}"
      KC_DB_USERNAME: "${KC_DB_USERNAME}"
      KC_DB_PASSWORD: "${KC_DB_PASSWORD}"
      KC_DB_SCHEMA: public

      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 7001

    ports:
      - "7001:7001"
    command: [ "start-dev", "--features=authorization,organization" ]
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - minha_rede

volumes:
  pgdata: {}

networks:
  minha_rede:
    driver: bridge